// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtWULw5mIlKGq2far11aLr-ujbg4d8on4',
    appId: '1:742348626956:web:c66bb06c1f798b5fc12229',
    messagingSenderId: '742348626956',
    projectId: 'flat-match-cd7c8',
    authDomain: 'flat-match-cd7c8.firebaseapp.com',
    storageBucket: 'flat-match-cd7c8.firebasestorage.app',
    measurementId: 'G-BJXD8RP5M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRQvw8lF-H2xCglUxKfWRzZ6MklfMDFzo',
    appId: '1:742348626956:android:097cd3e1966abf97c12229',
    messagingSenderId: '742348626956',
    projectId: 'flat-match-cd7c8',
    storageBucket: 'flat-match-cd7c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVXj59kRkFksc2i2xOcr9egZ1X7evGA7c',
    appId: '1:742348626956:ios:c5c009e0afd420c9c12229',
    messagingSenderId: '742348626956',
    projectId: 'flat-match-cd7c8',
    storageBucket: 'flat-match-cd7c8.firebasestorage.app',
    iosBundleId: 'com.example.flatMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVXj59kRkFksc2i2xOcr9egZ1X7evGA7c',
    appId: '1:742348626956:ios:c5c009e0afd420c9c12229',
    messagingSenderId: '742348626956',
    projectId: 'flat-match-cd7c8',
    storageBucket: 'flat-match-cd7c8.firebasestorage.app',
    iosBundleId: 'com.example.flatMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtWULw5mIlKGq2far11aLr-ujbg4d8on4',
    appId: '1:742348626956:web:b8e9b54f15aeffaec12229',
    messagingSenderId: '742348626956',
    projectId: 'flat-match-cd7c8',
    authDomain: 'flat-match-cd7c8.firebaseapp.com',
    storageBucket: 'flat-match-cd7c8.firebasestorage.app',
    measurementId: 'G-H7V7BMH68C',
  );
}
